# Meaning of params and more please see at https://github.com/leoleovich/grafsy/blob/master/README.md

clientSendInterval = 10

metricsPerSecond = 1000

graphiteAddr = "127.0.0.1:2003"
connectTimeout = 2

localBind = "127.0.0.1:3002"

log = "/var/log/grafsy/grafsy.log"

metricDir = "/tmp/grafsy"

retryFile = "/tmp/grafsy-retry"

sumPrefix = "SUM."
sumInterval = 60
sumsPerSecond = 60

avgPrefix = "AVG."
avgInterval = 60
avgsPerSecond = 60

monitoringPath = "servers.HOSTNAME.software"

allowedMetrics = "^((SUM|AVG).)?(nagios|powerline|backend|corporatesystems|carbon|games|hwlbs|powerline|servers|switches|network|test|cdn)\\.[-a-zA-Z0-9_]+\\.[-a-zA-Z0-9_\\(\\)\\.\\:\\/\\,\\{\\}=\\+\\#]+(\\s)[-0-9\\.eE+]+(\\s)[0-9]{10}$"
